### ISSUE TITLE
Issue while redefining 6DOF MARA to 3DOF MARA Robot

### ISSUE THREAD

**Issue by askkvn** [AcutronicRobotics/MARA#78]
I was trying to modify 6DOF to 3 DOF MARA, to simulate RL algorithm on local machine.
**Challenges I am facing**:
I have modified [mara_robot_gripper_140_train.urdf](https://github.com/AcutronicRobotics/MARA/blob/master/mara_description/urdf/reinforcement_learning/mara_robot_gripper_140_train.urdf) file to [mara_robot_gripper_140_3_dof.urdf](https://github.com/AcutronicRobotics/MARA/files/3162189/mara_robot_gripper_140_3_dof.urdf.txt). 
After modification, I am able to visualize robot in Rviz. But When I try to simulate it in gazebo with [gg_random.py](https://github.com/AcutronicRobotics/gym-gazebo2/blob/84c255df39d71f7db531d1e01a0d89553e5223a3/examples/MARA/gg_random.py) file, which calls  modified **mara.py** file.
It is giving following error:

```
[kevin@kvn-arc:~] py ros2learn/environments/gym-gazebo2/examples/MARA/gg_random.py -g
[INFO] [launch]: process[gazebo-1]: started with pid [20095]
[INFO] [launch]: process[spawn_mara.py-2]: started with pid [20096]
[INFO] [launch]: process[hros_cognition_mara_components-3]: started with pid [20097]
[INFO] [launch]: process[mara_contact_publisher-4]: started with pid [20098]
Unknown tag "contact" in /robot[@name='mara_3-DOF']/link[@name='table']
[ERROR] [launch]: process[hros_cognition_mara_components-3] process has died [pid 20097, exit code -11, cmd '/home/kevin/ros2_mara_ws/install/lib/hros_cognition_mara_components/hros_cognition_mara_components -motors /home/kevin/ros2_mara_ws/install/share/hros_cognition_mara_components/link_order.yaml'].
[ERROR] [launch]: process[gazebo-1] process has died [pid 20095, exit code 255, cmd 'gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/kevin/ros2learn/environments/gym-gazebo2/gym_gazebo2/worlds/empty__state_plugin__speed_up.world'].
```
Can you please help on this, how to run modified 3-DOF MARA robot? 

- Operating System:
  - Ubuntu 18.04 Bionic 
- ROS2 versions:
  - ROS2 Crystal 
- Failing component:
  - Gazebo 9 
#### Steps to reproduce issue
The modified mara.py file can be download from [here](https://github.com/AcutronicRobotics/MARA/files/3162352/mara.py.txt)

**Comment by nzlz** [comment]
Hi @askkvn ,

Could you pull latest changes from both MARA and gym-gazebo2? We have updated various important sections of the code recently. Anyway, I'll try to reproduce your setup tomorrow and come back with an answer.

Regards,

**Comment by nzlz** [comment]
## Solution
Hi again @askkvn , 

I created a new temporary branch ([3dof branch](https://github.com/AcutronicRobotics/MARA/tree/3dof)) that will solve your request. Just compile that one and your 3dof mara should work fine.

![mara_3dof](https://user-images.githubusercontent.com/16973377/57499117-9c41c780-7308-11e9-8e65-ac3ab1095309.gif)

---
## Explanation
### plugin (driver)
Our training plugin is different from the modular plugin used to run any trained policy or standard trajectories in the real robot (or simulated replica of the real). If you take a look at the available urdf files in the [reinforcement_learning folder](https://github.com/AcutronicRobotics/MARA/tree/master/mara_description/urdf/reinforcement_learning), you will notice every urdf has a `_run` and `_train` version, where only difference is that a different gazebo plugin is being called. Extra information available at [Docs/Drivers](https://acutronicrobotics.com/docs/technology/h-ros/api/level2/drivers).

So the main issue here is that you will need to create a a new training_3dof plugin which only affects 3 axis, not 6. I already did that in the 3dof branch i mentioned above, and updated the urdf accordingly. Note that we need to use the [third axis too](https://github.com/AcutronicRobotics/MARA/blob/51b8725d9f2d324d358f07f8a9deb8bdbae168bc/mara_description/urdf/reinforcement_learning/mara_robot_gripper_140_3_dof.urdf#L493), if we only control 2 axes we would lose control of the last mara joint and the end link would fall.

In case you just want to use 2 axes only, you can remove the third one from the plugin call, but you will also need to remove the joint of the third motor and make sure links are attached properly.

### hros_cognition
The `hros_cognition_mara_components` package is a package that takes care of combining individual goals and states of all the axes and publishes/subscribes to JointTrajectory* messages. You can control the robot without cognition, publishing/subscribir to axis specific topics/services. In gym-gazebo2, we use the cognition mainly for convenience (performance issues related to cpp implementation too). 

You just need to update the configuration file used to launch the main node of this package to reflect the 3DoF MARA you want to control. I already did that in the 3dof branch [here](https://github.com/AcutronicRobotics/MARA/blob/3dof/hros_cognition_mara_components/config/motors.yaml). I did it this way so that you would not need to update gym-gazebo2, but you can create a new file instead of modifying that one, and update the call to the cognition node in the LaunchDescription created at [gym-gazebo2/utils/ut_launch](https://github.com/AcutronicRobotics/gym-gazebo2/blob/84c255df39d71f7db531d1e01a0d89553e5223a3/gym_gazebo2/utils/ut_launch.py#L147).

Changes summary:
- 3dof training plugin
- hros_cognition config file

**Comment by askkvn** [comment]
Thanks @nzlz for your valuable support. Now, we are able to simulate 3DOF MARA in local machine. Through your detailed explanation, we are able to understand MARA ROS2 structure thoroughly.
